# Generated by Django 6.1.1 on 2026-09-05 14:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "case_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="رقم القضية"
                    ),
                ),
                (
                    "judicial_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="الرقم القضائي الرسمي",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=500, verbose_name="عنوان القضية"),
                ),
                (
                    "case_type",
                    models.CharField(max_length=30, verbose_name="نوع القضية"),
                ),
                ("court", models.CharField(max_length=200, verbose_name="المحكمة")),
                (
                    "circuit",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الدائرة"
                    ),
                ),
                ("status", models.CharField(max_length=20, verbose_name="الحالة")),
                ("opened_date", models.DateField(verbose_name="تاريخ فتح القضية")),
                (
                    "closed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الإغلاق"
                    ),
                ),
                (
                    "subject_matter",
                    models.TextField(blank=True, verbose_name="موضوع القضية"),
                ),
                (
                    "tags",
                    models.CharField(blank=True, max_length=500, verbose_name="وسوم"),
                ),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "قضية",
                "verbose_name_plural": "القضايا",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="الاسم الكامل"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "client_code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="كود العميل"
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="الرقم القومي",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الميلاد"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="العنوان")),
                (
                    "job",
                    models.CharField(blank=True, max_length=100, verbose_name="المهنة"),
                ),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "عميل",
                "verbose_name_plural": "العملاء",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ClientFile",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "file_type",
                    models.CharField(max_length=20, verbose_name="نوع الملف"),
                ),
                (
                    "uploaded_by",
                    models.CharField(max_length=10, verbose_name="رُفع بواسطة"),
                ),
                (
                    "display_name",
                    models.CharField(max_length=255, verbose_name="الاسم"),
                ),
                (
                    "folder_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="المجلد الفرعي",
                    ),
                ),
                (
                    "gdrive_url",
                    models.URLField(blank=True, verbose_name="رابط Google Drive"),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="مرئي للعميل"),
                ),
                (
                    "admin_comment",
                    models.TextField(blank=True, verbose_name="تعليق الأدمن"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="حجم الملف (bytes)"
                    ),
                ),
                ("created_at", models.DateTimeField(verbose_name="تاريخ الرفع")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "مستند عميل",
                "verbose_name_plural": "مستندات العملاء",
            },
        ),
        migrations.CreateModel(
            name="ClientPopupMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "message_type",
                    models.CharField(
                        default="brochure", max_length=20, verbose_name="النوع"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                ("body", models.TextField(blank=True, verbose_name="النص")),
                (
                    "link",
                    models.CharField(blank=True, max_length=500, verbose_name="الرابط"),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(default=0, verbose_name="الأولوية"),
                ),
                (
                    "approved_by_admin",
                    models.BooleanField(default=False, verbose_name="اعتماد الأدمن"),
                ),
                (
                    "approved_by_lawyer",
                    models.BooleanField(default=False, verbose_name="اعتماد المحامي"),
                ),
                (
                    "dismissed_by_client",
                    models.BooleanField(
                        default=False, verbose_name="تم إخفاؤها من العميل"
                    ),
                ),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="popup_messages",
                        to="clients.case",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="popup_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "رسالة منبثقة للعميل",
                "verbose_name_plural": "الرسائل المنبثقة للعملاء",
            },
        ),
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "subject",
                    models.CharField(max_length=300, verbose_name="موضوع الاستشارة"),
                ),
                ("question_text", models.TextField(verbose_name="نص الاستشارة")),
                ("status", models.CharField(max_length=20, verbose_name="الحالة")),
                ("admin_reply", models.TextField(blank=True, verbose_name="رد المكتب")),
                (
                    "replied_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الرد"
                    ),
                ),
                ("is_urgent", models.BooleanField(default=False, verbose_name="عاجلة")),
                ("created_at", models.DateTimeField(verbose_name="تاريخ الإرسال")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "استشارة",
                "verbose_name_plural": "الاستشارات",
            },
        ),
        migrations.CreateModel(
            name="FileComment",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "author_type",
                    models.CharField(max_length=10, verbose_name="نوع الكاتب"),
                ),
                ("text", models.TextField(verbose_name="نص التعليق")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت التعليق"),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="clients.clientfile",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="clients.filecomment",
                    ),
                ),
            ],
            options={
                "verbose_name": "تعليق على مستند",
                "verbose_name_plural": "تعليقات المستندات",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "invoice_num",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم الفاتورة"
                    ),
                ),
                ("issue_date", models.DateField(verbose_name="تاريخ الإصدار")),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الاستحقاق"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="مبلغ الفاتورة"
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="نسبة الضريبة %",
                    ),
                ),
                ("status", models.CharField(max_length=15, verbose_name="الحالة")),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="clients.case",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "فاتورة",
                "verbose_name_plural": "الفواتير",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "notif_type",
                    models.CharField(
                        default="general", max_length=20, verbose_name="النوع"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                ("body", models.TextField(blank=True, verbose_name="النص")),
                (
                    "link",
                    models.CharField(blank=True, max_length=500, verbose_name="الرابط"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="مقروء")),
                ("created_at", models.DateTimeField()),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "إشعار",
                "verbose_name_plural": "الإشعارات",
            },
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "party_type",
                    models.CharField(max_length=20, verbose_name="نوع الطرف"),
                ),
                (
                    "full_name",
                    models.CharField(max_length=300, verbose_name="الاسم الكامل"),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="الجهة / المؤسسة"
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="الرقم الوطني / السجل"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="الهاتف"),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True, verbose_name="العنوان")),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parties",
                        to="clients.case",
                    ),
                ),
            ],
            options={
                "verbose_name": "طرف",
                "verbose_name_plural": "أطراف القضايا",
            },
        ),
        migrations.CreateModel(
            name="PowerOfAttorney",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "poa_type",
                    models.CharField(
                        default="special", max_length=30, verbose_name="نوع التوكيل"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="عنوان التوكيل"),
                ),
                (
                    "poa_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="رقم التوكيل"
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الإصدار"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الانتهاء"
                    ),
                ),
                (
                    "notary_office",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="مكتب التوثيق"
                    ),
                ),
                (
                    "visible_fields",
                    models.JSONField(
                        blank=True, default=list, verbose_name="الحقول الظاهرة للعميل"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="powers_of_attorney",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "توكيل",
                "verbose_name_plural": "التوكيلات",
            },
        ),
        migrations.CreateModel(
            name="CasePortalLink",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "is_visible_to_client",
                    models.BooleanField(default=False, verbose_name="مرئي للعميل"),
                ),
                (
                    "shared_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="الحقول المشتركة مع العميل",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_links",
                        to="clients.case",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ربط قضية بعميل",
                "verbose_name_plural": "روابط القضايا بالعملاء",
                "unique_together": {("case", "client")},
            },
        ),
    ]
