# Generated by Django 5.1.3 on 2026-09-13 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "session_number",
                    models.PositiveIntegerField(default=1, verbose_name="رقم الجلسة"),
                ),
                ("session_date", models.DateField(verbose_name="تاريخ الجلسة")),
                (
                    "session_time",
                    models.TimeField(blank=True, null=True, verbose_name="وقت الجلسة"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="مكان الجلسة"
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="نتيجة الجلسة"
                    ),
                ),
                ("minutes", models.TextField(blank=True, verbose_name="محضر الجلسة")),
                (
                    "ruling",
                    models.TextField(blank=True, verbose_name="القرار / الحكم الصادر"),
                ),
                (
                    "next_session_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="موعد الجلسة القادمة"
                    ),
                ),
                (
                    "postponement_reason",
                    models.TextField(blank=True, verbose_name="سبب التأجيل"),
                ),
                (
                    "requests",
                    models.TextField(blank=True, verbose_name="الطلبات المقدمة"),
                ),
                (
                    "permits",
                    models.TextField(blank=True, verbose_name="التصاريح المطلوبة"),
                ),
                (
                    "preparations",
                    models.TextField(
                        blank=True, verbose_name="استعدادات الجلسة القادمة"
                    ),
                ),
                (
                    "obstacles",
                    models.TextField(blank=True, verbose_name="عقبات وتحديات"),
                ),
                (
                    "tags",
                    models.CharField(blank=True, max_length=500, verbose_name="وسوم"),
                ),
                (
                    "is_visible_to_client",
                    models.BooleanField(default=False, verbose_name="مرئية للعميل"),
                ),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="clients.case",
                    ),
                ),
            ],
            options={
                "verbose_name": "جلسة",
                "verbose_name_plural": "الجلسات",
                "ordering": ["session_date", "session_number"],
            },
        ),
    ]
