# Generated by Django 5.1.3 on 2026-09-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.PositiveIntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="كود الموظف"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="الاسم")),
                (
                    "role",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="المسمى الوظيفي"
                    ),
                ),
                (
                    "sector_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="معرّف القطاع"
                    ),
                ),
                (
                    "department_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="معرّف القسم"
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, verbose_name="السيرة الذاتية/المهام"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="الهاتف"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد الإلكتروني"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "avatar_model",
                    models.CharField(
                        blank=True,
                        default="avatar_1",
                        max_length=50,
                        verbose_name="الأفاتار",
                    ),
                ),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "موظف",
                "verbose_name_plural": "الموظفون",
            },
        ),
    ]
