# Generated by Django 5.1.3 on 2026-09-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lawyer",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "username",
                    models.CharField(max_length=150, verbose_name="اسم المستخدم"),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="الاسم الكامل"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد الإلكتروني"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="الرقم القومي",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الميلاد"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="العنوان")),
                (
                    "job",
                    models.CharField(blank=True, max_length=100, verbose_name="المهنة"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "password_hash",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="كلمة المرور (هاش)"
                    ),
                ),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "محامي (زبون)",
                "verbose_name_plural": "المحامون (زبائن)",
            },
        ),
    ]
