# Generated by Django 5.1.3 on 2026-09-14 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0006_lawyer"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseSection",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "قسم موضوعي",
                "verbose_name_plural": "الأقسام الموضوعية",
            },
        ),
        migrations.CreateModel(
            name="CourtAuthority",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=300)),
                ("authority_type", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("working_hours", models.CharField(blank=True, max_length=100)),
                ("access_method", models.CharField(blank=True, max_length=200)),
                ("access_duration", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "محكمة / هيئة",
                "verbose_name_plural": "المحاكم والهيئات",
            },
        ),
        migrations.CreateModel(
            name="CourtSector",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "قطاع ميداني",
                "verbose_name_plural": "القطاعات الميدانية",
            },
        ),
        migrations.CreateModel(
            name="CourtDivision",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=300)),
                ("division_type", models.CharField(blank=True, max_length=20)),
                ("judge_name", models.CharField(blank=True, max_length=200)),
                ("working_hours", models.CharField(blank=True, max_length=100)),
                ("review_hours", models.CharField(blank=True, max_length=100)),
                ("location_inside", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "court",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="divisions",
                        to="clients.courtauthority",
                    ),
                ),
            ],
            options={
                "verbose_name": "دائرة / إدارة",
                "verbose_name_plural": "الدوائر والإدارات",
            },
        ),
        migrations.CreateModel(
            name="CourtEntity",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=300)),
                ("entity_type", models.CharField(blank=True, max_length=20)),
                ("job_title", models.CharField(blank=True, max_length=200)),
                ("job_grade", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entities",
                        to="clients.courtdivision",
                    ),
                ),
            ],
            options={
                "verbose_name": "جهة / موظف",
                "verbose_name_plural": "الجهات والموظفون",
            },
        ),
        migrations.AddField(
            model_name="courtauthority",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courts",
                to="clients.courtsector",
            ),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("kind", models.CharField(default="quick", max_length=15)),
                ("title", models.CharField(max_length=500)),
                ("status", models.CharField(blank=True, max_length=15)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("responsible_party", models.CharField(blank=True, max_length=200)),
                ("priority", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("ai_suggested", models.BooleanField(default=False)),
                ("client_id", models.CharField(blank=True, default="", max_length=40)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="all_tasks",
                        to="clients.case",
                    ),
                ),
                (
                    "court_authorities",
                    models.ManyToManyField(
                        blank=True, related_name="tasks", to="clients.courtauthority"
                    ),
                ),
                (
                    "court_divisions",
                    models.ManyToManyField(
                        blank=True, related_name="tasks", to="clients.courtdivision"
                    ),
                ),
                (
                    "entities",
                    models.ManyToManyField(
                        blank=True, related_name="tasks", to="clients.courtentity"
                    ),
                ),
                (
                    "linked_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_tasks",
                        to="clients.task",
                    ),
                ),
                (
                    "sections",
                    models.ManyToManyField(
                        blank=True, related_name="tasks", to="clients.casesection"
                    ),
                ),
                (
                    "sectors",
                    models.ManyToManyField(
                        blank=True, related_name="tasks", to="clients.courtsector"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unified_tasks",
                        to="clients.session",
                    ),
                ),
            ],
            options={
                "verbose_name": "مهمة",
                "verbose_name_plural": "المهام",
            },
        ),
        migrations.CreateModel(
            name="TaskStep",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=400)),
                ("status", models.CharField(blank=True, max_length=15)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("executor", models.CharField(blank=True, max_length=200)),
                (
                    "expense",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="clients.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "خطوة",
                "verbose_name_plural": "الخطوات",
            },
        ),
        migrations.CreateModel(
            name="TaskAction",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=400)),
                ("type", models.CharField(default="action", max_length=10)),
                ("is_done", models.BooleanField(default=False)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "expense",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="clients.taskstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "إجراء",
                "verbose_name_plural": "الإجراءات",
            },
        ),
    ]
