# Generated by Django 5.1.3 on 2026-09-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "clients",
            "0007_casesection_courtauthority_courtsector_courtdivision_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="synced_to_lawfirm",
            field=models.BooleanField(
                default=False, verbose_name="تم إرسالها لـ lawfirm_portal"
            ),
        ),
    ]
